ENV["SINATRA_ENV"] ||= "development"

require_relative './config/environment'
require 'sinatra/activerecord/rake'


desc 'open console'
task :console do 
  puts "Getting ready to open console"
  Pry.start
end 