co1 = CarOwner.new("Meghann")
co2 = CarOwner.new("Greg")
co3 = CarOwner.new("Jallen")

m1 = Mechanic.new("Steven", "clunker")
m2 = Mechanic.new("Caryn", "antique")
m3 = Mechanic.new("Justin", "exotic")

c1 = Car.new("Toyota", "Camry", "clunker", m1, co1)
c2 = Car.new("Ford", "Model T", "antique", m2, co2)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)
c3 = Car.new("Ferrari", "Portofino", "exotic", m3, co3)